version: "3.8"

services:
  backend:
    image: "medicsign/backend:latest"
    build: ./backend/express/
    restart: unless-stopped
    env_file: ./backend/express/.env
    ports:
      - 3000:3000
  frontend:
    image: "medicsign/frontend:latest"
    build: ./frontend/
    restart: unless-stopped
    ports:
      - 3001:3000
